const footerBlurbs = {
    day_1: "Powered by coffee and last-minute motivation ☕",
    day_2: "Survived 3 assignment deadlines to bring you this 💼",
    day_3: "This page powered by instant noodles & good vibes 🍜✨",
    day_4: "Studying? Or just scrolling again? We won't judge 😅",
    day_5: "Melbourne weather: unpredictable, just like our study schedule 🌦️",
    day_6: "When in doubt, add more coffee to the equation ☕",
    day_7: "Saving money one free campus event at a time 💸",
    day_8: "Library vibes: quiet but secretly judging your snack choices 📚",
    day_9: "Student life: where 'I'll do it later' is a lifestyle choice ⏰",
    day_10: "Melbourne trams: the real MVPs of student transport 🚋",
    day_11: "When your bank account is as empty as your coffee cup 💸",
    day_12: "Student budget: where instant noodles are gourmet cuisine 🍜",
    day_13: "Campus squirrels: the real campus celebrities 🐿️",
    day_14: "When your study playlist is longer than your attention span 🎵",
    day_15: "Melbourne coffee: the real reason we survive uni ☕",
    day_16: "Student life: where 2am is a reasonable bedtime 🌙",
    day_17: "When your notes look like they were written by a squirrel 📝",
    day_18: "Campus life: where every bench is a potential study spot 🪑",
    day_19: "Student budget: where 'splurging' means buying name-brand ramen 💸",
    day_20: "When your highlighters have more colors than your social life 🖍️",
    day_21: "Melbourne weather: perfect for staying in and studying 🌧️",
    day_22: "Student life: where 'I'll sleep when I'm dead' is a motto 😴",
    day_23: "When your coffee addiction is stronger than your willpower ☕",
    day_24: "Campus squirrels: the real campus influencers 🐿️",
    day_25: "Student budget: where 'eating out' means the campus cafeteria 💸",
    day_26: "When your study snacks are more organized than your notes 🍪",
    day_27: "Melbourne trams: the real study halls on wheels 🚋",
    day_28: "Student life: where 'I'll do it tomorrow' is a daily mantra ⏰",
    day_29: "When your highlighters run out before your motivation 🖍️",
    day_30: "Campus life: where every power outlet is prime real estate 🔌",
    day_31: "Student budget: where 'splurging' means buying coffee ☕",
    day_32: "When your study playlist is your only friend 🎵",
    day_33: "Melbourne weather: perfect for staying in and procrastinating 🌧️",
    day_34: "Student life: where 'I'll sleep when I'm retired' is a goal 😴",
    day_35: "When your coffee cup is your most prized possession ☕",
    day_36: "Campus squirrels: the real campus celebrities 🐿️",
    day_37: "Student budget: where 'eating out' means the library vending machine 💸",
    day_38: "When your study snacks are more important than your notes 🍪",
    day_39: "Melbourne trams: the real mobile study spaces 🚋",
    day_40: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_41: "When your highlighters are your only source of color 🖍️",
    day_42: "Campus life: where every bench is a potential nap spot 🪑",
    day_43: "Student budget: where 'splurging' means buying name-brand coffee ☕",
    day_44: "When your study playlist is your only motivation 🎵",
    day_45: "Melbourne weather: perfect for staying in and binging Netflix 🌧️",
    day_46: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_47: "When your coffee addiction is your only constant ☕",
    day_48: "Campus squirrels: the real campus royalty 🐿️",
    day_49: "Student budget: where 'eating out' means the campus food court 💸",
    day_50: "When your study snacks are your only joy 🍪",
    day_51: "Melbourne trams: the real mobile libraries 🚋",
    day_52: "Student life: where 'I'll do it eventually' is a promise ⏰",
    day_53: "When your highlighters are your only friends 🖍️",
    day_54: "Campus life: where every power outlet is a treasure 🔌",
    day_55: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_56: "When your study playlist is your only companion 🎵",
    day_57: "Melbourne weather: perfect for staying in and avoiding reality 🌧️",
    day_58: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_59: "When your coffee cup is your only constant ☕",
    day_60: "Campus squirrels: the real campus legends 🐿️",
    day_61: "Student budget: where 'eating out' means the campus cafe 💸",
    day_62: "When your study snacks are your only happiness 🍪",
    day_63: "Melbourne trams: the real mobile study halls 🚋",
    day_64: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_65: "When your highlighters are your only source of joy 🖍️",
    day_66: "Campus life: where every bench is a potential study desk 🪑",
    day_67: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_68: "When your study playlist is your only motivation 🎵",
    day_69: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_70: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_71: "When your coffee addiction is your only personality trait ☕",
    day_72: "Campus squirrels: the real campus influencers 🐿️",
    day_73: "Student budget: where 'eating out' means the campus food truck 💸",
    day_74: "When your study snacks are your only comfort 🍪",
    day_75: "Melbourne trams: the real mobile classrooms 🚋",
    day_76: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_77: "When your highlighters are your only source of color 🖍️",
    day_78: "Campus life: where every power outlet is a blessing 🔌",
    day_79: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_80: "When your study playlist is your only friend 🎵",
    day_81: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_82: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_83: "When your coffee cup is your only companion ☕",
    day_84: "Campus squirrels: the real campus celebrities 🐿️",
    day_85: "Student budget: where 'eating out' means the campus food court 💸",
    day_86: "When your study snacks are your only joy 🍪",
    day_87: "Melbourne trams: the real mobile study spaces 🚋",
    day_88: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_89: "When your highlighters are your only source of happiness 🖍️",
    day_90: "Campus life: where every bench is a potential study spot 🪑",
    day_91: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_92: "When your study playlist is your only motivation 🎵",
    day_93: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_94: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_95: "When your coffee addiction is your only constant ☕",
    day_96: "Campus squirrels: the real campus royalty 🐿️",
    day_97: "Student budget: where 'eating out' means the campus cafe 💸",
    day_98: "When your study snacks are your only happiness 🍪",
    day_99: "Melbourne trams: the real mobile libraries 🚋",
    day_100: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_101: "When your highlighters are your only source of joy 🖍️",
    day_102: "Campus life: where every power outlet is a treasure 🔌",
    day_103: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_104: "When your study playlist is your only motivation 🎵",
    day_105: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_106: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_107: "When your coffee addiction is your only personality trait ☕",
    day_108: "Campus squirrels: the real campus influencers 🐿️",
    day_109: "Student budget: where 'eating out' means the campus food truck 💸",
    day_110: "When your study snacks are your only comfort 🍪",
    day_111: "Melbourne trams: the real mobile classrooms 🚋",
    day_112: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_113: "When your highlighters are your only source of color 🖍️",
    day_114: "Campus life: where every power outlet is a blessing 🔌",
    day_115: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_116: "When your study playlist is your only friend 🎵",
    day_117: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_118: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_119: "When your coffee cup is your only companion ☕",
    day_120: "Campus squirrels: the real campus celebrities 🐿️",
    day_121: "Student budget: where 'eating out' means the campus food court 💸",
    day_122: "When your study snacks are your only joy 🍪",
    day_123: "Melbourne trams: the real mobile study spaces 🚋",
    day_124: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_125: "When your highlighters are your only source of happiness 🖍️",
    day_126: "Campus life: where every bench is a potential study spot 🪑",
    day_127: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_128: "When your study playlist is your only motivation 🎵",
    day_129: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_130: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_131: "When your coffee addiction is your only constant ☕",
    day_132: "Campus squirrels: the real campus royalty 🐿️",
    day_133: "Student budget: where 'eating out' means the campus cafe 💸",
    day_134: "When your study snacks are your only happiness 🍪",
    day_135: "Melbourne trams: the real mobile libraries 🚋",
    day_136: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_137: "When your highlighters are your only source of joy 🖍️",
    day_138: "Campus life: where every power outlet is a treasure 🔌",
    day_139: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_140: "When your study playlist is your only motivation 🎵",
    day_141: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_142: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_143: "When your coffee addiction is your only personality trait ☕",
    day_144: "Campus squirrels: the real campus influencers 🐿️",
    day_145: "Student budget: where 'eating out' means the campus food truck 💸",
    day_146: "When your study snacks are your only comfort 🍪",
    day_147: "Melbourne trams: the real mobile classrooms 🚋",
    day_148: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_149: "When your highlighters are your only source of color 🖍️",
    day_150: "Campus life: where every power outlet is a blessing 🔌",
    day_151: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_152: "When your study playlist is your only friend 🎵",
    day_153: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_154: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_155: "When your coffee cup is your only companion ☕",
    day_156: "Campus squirrels: the real campus celebrities 🐿️",
    day_157: "Student budget: where 'eating out' means the campus food court 💸",
    day_158: "When your study snacks are your only joy 🍪",
    day_159: "Melbourne trams: the real mobile study spaces 🚋",
    day_160: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_161: "When your highlighters are your only source of happiness 🖍️",
    day_162: "Campus life: where every bench is a potential study spot 🪑",
    day_163: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_164: "When your study playlist is your only motivation 🎵",
    day_165: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_166: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_167: "When your coffee addiction is your only constant ☕",
    day_168: "Campus squirrels: the real campus royalty 🐿️",
    day_169: "Student budget: where 'eating out' means the campus cafe 💸",
    day_170: "When your study snacks are your only happiness 🍪",
    day_171: "Melbourne trams: the real mobile libraries 🚋",
    day_172: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_173: "When your highlighters are your only source of joy 🖍️",
    day_174: "Campus life: where every power outlet is a treasure 🔌",
    day_175: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_176: "When your study playlist is your only motivation 🎵",
    day_177: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_178: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_179: "When your coffee addiction is your only personality trait ☕",
    day_180: "Campus squirrels: the real campus influencers 🐿️",
    day_181: "Student budget: where 'eating out' means the campus food truck 💸",
    day_182: "When your study snacks are your only comfort 🍪",
    day_183: "Melbourne trams: the real mobile classrooms 🚋",
    day_184: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_185: "When your highlighters are your only source of color 🖍️",
    day_186: "Campus life: where every power outlet is a blessing 🔌",
    day_187: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_188: "When your study playlist is your only friend 🎵",
    day_189: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_190: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_191: "When your coffee cup is your only companion ☕",
    day_192: "Campus squirrels: the real campus celebrities 🐿️",
    day_193: "Student budget: where 'eating out' means the campus food court 💸",
    day_194: "When your study snacks are your only joy 🍪",
    day_195: "Melbourne trams: the real mobile study spaces 🚋",
    day_196: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_197: "When your highlighters are your only source of happiness 🖍️",
    day_198: "Campus life: where every bench is a potential study spot 🪑",
    day_199: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_200: "When your study playlist is your only motivation 🎵",
    day_201: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_202: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_203: "When your coffee addiction is your only constant ☕",
    day_204: "Campus squirrels: the real campus royalty 🐿️",
    day_205: "Student budget: where 'eating out' means the campus cafe 💸",
    day_206: "When your study snacks are your only happiness 🍪",
    day_207: "Melbourne trams: the real mobile libraries 🚋",
    day_208: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_209: "When your highlighters are your only source of joy 🖍️",
    day_210: "Campus life: where every power outlet is a treasure 🔌",
    day_211: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_212: "When your study playlist is your only motivation 🎵",
    day_213: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_214: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_215: "When your coffee addiction is your only personality trait ☕",
    day_216: "Campus squirrels: the real campus influencers 🐿️",
    day_217: "Student budget: where 'eating out' means the campus food truck 💸",
    day_218: "When your study snacks are your only comfort 🍪",
    day_219: "Melbourne trams: the real mobile classrooms 🚋",
    day_220: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_221: "When your highlighters are your only source of color 🖍️",
    day_222: "Campus life: where every power outlet is a blessing 🔌",
    day_223: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_224: "When your study playlist is your only friend 🎵",
    day_225: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_226: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_227: "When your coffee cup is your only companion ☕",
    day_228: "Campus squirrels: the real campus celebrities 🐿️",
    day_229: "Student budget: where 'eating out' means the campus food court 💸",
    day_230: "When your study snacks are your only joy 🍪",
    day_231: "Melbourne trams: the real mobile study spaces 🚋",
    day_232: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_233: "When your highlighters are your only source of happiness 🖍️",
    day_234: "Campus life: where every bench is a potential study spot 🪑",
    day_235: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_236: "When your study playlist is your only motivation 🎵",
    day_237: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_238: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_239: "When your coffee addiction is your only constant ☕",
    day_240: "Campus squirrels: the real campus royalty 🐿️",
    day_241: "Student budget: where 'eating out' means the campus cafe 💸",
    day_242: "When your study snacks are your only happiness 🍪",
    day_243: "Melbourne trams: the real mobile libraries 🚋",
    day_244: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_245: "When your highlighters are your only source of joy 🖍️",
    day_246: "Campus life: where every power outlet is a treasure 🔌",
    day_247: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_248: "When your study playlist is your only motivation 🎵",
    day_249: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_250: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_251: "When your coffee addiction is your only personality trait ☕",
    day_252: "Campus squirrels: the real campus influencers 🐿️",
    day_253: "Student budget: where 'eating out' means the campus food truck 💸",
    day_254: "When your study snacks are your only comfort 🍪",
    day_255: "Melbourne trams: the real mobile classrooms 🚋",
    day_256: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_257: "When your highlighters are your only source of color 🖍️",
    day_258: "Campus life: where every power outlet is a blessing 🔌",
    day_259: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_260: "When your study playlist is your only friend 🎵",
    day_261: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_262: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_263: "When your coffee cup is your only companion ☕",
    day_264: "Campus squirrels: the real campus celebrities 🐿️",
    day_265: "Student budget: where 'eating out' means the campus food court 💸",
    day_266: "When your study snacks are your only joy 🍪",
    day_267: "Melbourne trams: the real mobile study spaces 🚋",
    day_268: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_269: "When your highlighters are your only source of happiness 🖍️",
    day_270: "Campus life: where every bench is a potential study spot 🪑",
    day_271: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_272: "When your study playlist is your only motivation 🎵",
    day_273: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_274: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_275: "When your coffee addiction is your only constant ☕",
    day_276: "Campus squirrels: the real campus royalty 🐿️",
    day_277: "Student budget: where 'eating out' means the campus cafe 💸",
    day_278: "When your study snacks are your only happiness 🍪",
    day_279: "Melbourne trams: the real mobile libraries 🚋",
    day_280: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_281: "When your highlighters are your only source of joy 🖍️",
    day_282: "Campus life: where every power outlet is a treasure 🔌",
    day_283: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_284: "When your study playlist is your only motivation 🎵",
    day_285: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_286: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_287: "When your coffee addiction is your only personality trait ☕",
    day_288: "Campus squirrels: the real campus influencers 🐿️",
    day_289: "Student budget: where 'eating out' means the campus food truck 💸",
    day_290: "When your study snacks are your only comfort 🍪",
    day_291: "Melbourne trams: the real mobile classrooms 🚋",
    day_292: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_293: "When your highlighters are your only source of color 🖍️",
    day_294: "Campus life: where every power outlet is a blessing 🔌",
    day_295: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_296: "When your study playlist is your only friend 🎵",
    day_297: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_298: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_299: "When your coffee cup is your only companion ☕",
    day_300: "Campus squirrels: the real campus celebrities 🐿️",
    day_301: "Student budget: where 'eating out' means the campus food court 💸",
    day_302: "When your study snacks are your only joy 🍪",
    day_303: "Melbourne trams: the real mobile study spaces 🚋",
    day_304: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_305: "When your highlighters are your only source of happiness 🖍️",
    day_306: "Campus life: where every bench is a potential study spot 🪑",
    day_307: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_308: "When your study playlist is your only motivation 🎵",
    day_309: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_310: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_311: "When your coffee addiction is your only constant ☕",
    day_312: "Campus squirrels: the real campus royalty 🐿️",
    day_313: "Student budget: where 'eating out' means the campus cafe 💸",
    day_314: "When your study snacks are your only happiness 🍪",
    day_315: "Melbourne trams: the real mobile libraries 🚋",
    day_316: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_317: "When your highlighters are your only source of joy 🖍️",
    day_318: "Campus life: where every power outlet is a treasure 🔌",
    day_319: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_320: "When your study playlist is your only motivation 🎵",
    day_321: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_322: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_323: "When your coffee addiction is your only personality trait ☕",
    day_324: "Campus squirrels: the real campus influencers 🐿️",
    day_325: "Student budget: where 'eating out' means the campus food truck 💸",
    day_326: "When your study snacks are your only comfort 🍪",
    day_327: "Melbourne trams: the real mobile classrooms 🚋",
    day_328: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_329: "When your highlighters are your only source of color 🖍️",
    day_330: "Campus life: where every power outlet is a blessing 🔌",
    day_331: "Student budget: where 'splurging' means buying coffee grounds ☕",
    day_332: "When your study playlist is your only friend 🎵",
    day_333: "Melbourne weather: perfect for staying in and avoiding responsibilities 🌧️",
    day_334: "Student life: where 'I'll sleep when I'm rich' is a goal 😴",
    day_335: "When your coffee cup is your only companion ☕",
    day_336: "Campus squirrels: the real campus celebrities 🐿️",
    day_337: "Student budget: where 'eating out' means the campus food court 💸",
    day_338: "When your study snacks are your only joy 🍪",
    day_339: "Melbourne trams: the real mobile study spaces 🚋",
    day_340: "Student life: where 'I'll do it later' is a way of life ⏰",
    day_341: "When your highlighters are your only source of happiness 🖍️",
    day_342: "Campus life: where every bench is a potential study spot 🪑",
    day_343: "Student budget: where 'splurging' means buying coffee beans ☕",
    day_344: "When your study playlist is your only motivation 🎵",
    day_345: "Melbourne weather: perfect for staying in and avoiding the world 🌧️",
    day_346: "Student life: where 'I'll sleep when I'm successful' is a dream 😴",
    day_347: "When your coffee addiction is your only constant ☕",
    day_348: "Campus squirrels: the real campus royalty 🐿️",
    day_349: "Student budget: where 'eating out' means the campus cafe 💸",
    day_350: "When your study snacks are your only happiness 🍪",
    day_351: "Melbourne trams: the real mobile libraries 🚋",
    day_352: "Student life: where 'I'll do it soon' is a commitment ⏰",
    day_353: "When your highlighters are your only source of joy 🖍️",
    day_354: "Campus life: where every power outlet is a treasure 🔌",
    day_355: "Student budget: where 'splurging' means buying coffee filters ☕",
    day_356: "When your study playlist is your only motivation 🎵",
    day_357: "Melbourne weather: perfect for staying in and avoiding people 🌧️",
    day_358: "Student life: where 'I'll sleep when I'm famous' is a plan 😴",
    day_359: "When your coffee addiction is your only personality trait ☕",
    day_360: "Campus squirrels: the real campus influencers 🐿️",
    day_361: "Student budget: where 'eating out' means the campus food truck 💸",
    day_362: "When your study snacks are your only comfort 🍪",
    day_363: "Melbourne trams: the real mobile classrooms 🚋",
    day_364: "Student life: where 'I'll do it eventually' is a lifestyle ⏰",
    day_365: "When your highlighters are your only source of color 🖍️"
};

// Function to get today's blurb
function getTodaysBlurb() {
    const today = new Date();
    const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / (1000 * 60 * 60 * 24));
    const dayKey = `day_${dayOfYear}`;
    return footerBlurbs[dayKey] || "Powered by student determination and coffee ☕";
}

export { footerBlurbs, getTodaysBlurb }; 